server:
  port: 8801

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      username: ${MONGO_DB_USERNAME:admin}
      password: ${MONGO_DB_PASSWORD:admin}
      database: oj_case
      port: 27017
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 2MB
case:
  secret-key: ${SECRET_KEY:}
